### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-ecowitt

### ISSUE THREAD

**Issue by gwurb** [spatialdude/homebridge-ecowitt#22]
**Describe Your Problem:**
homebridge-ecowitt plugin is not loaded on homebridge startup

Homebridge IP address is: 192.168.0.10

Device: GW1000 , outdoor sensor and two indoor sensors

WS View settings:
Server: Customized
Enable
Protocol Type Same as: Ecowitt
Server IP: 192.168.0.10
Path: /weather/data/
Port: 4199
Upload interval: 60 Seconds

**Logs:**
[31/10/2022, 11:45:05 am] [Homebridge UI] Changes to config.json saved.
[31/10/2022, 11:45:08 am] [Homebridge UI] Homebridge restart request received
[31/10/2022, 11:45:08 am] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[31/10/2022, 11:45:08 am] [Homebridge UI] Sending SIGTERM to Homebridge
[31/10/2022, 11:45:08 am] Got SIGTERM, shutting down Homebridge...
[31/10/2022, 11:45:13 am] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[31/10/2022, 11:45:18 am] [HB Supervisor] Restarting Homebridge...
[31/10/2022, 11:45:18 am] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[31/10/2022, 11:45:18 am] [HB Supervisor] Started Homebridge v1.5.1 with PID: 8776
[31/10/2022, 11:45:18 am] Loaded config.json with 1 accessories and 3 platforms.
[31/10/2022, 11:45:18 am] Loaded 1 cached accessories from cachedAccessories.
[31/10/2022, 11:45:18 am] ---
[31/10/2022, 11:45:19 am] ====================
[31/10/2022, 11:45:19 am] ERROR LOADING PLUGIN homebridge-ecowitt:
[31/10/2022, 11:45:19 am] TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (/var/lib/homebridge/node_modules/homebridge-ecowitt/node_modules/restify/lib/request.js:848:30)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ecowitt/node_modules/restify/lib/server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ecowitt/node_modules/restify/lib/index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
[31/10/2022, 11:45:19 am] ====================
[31/10/2022, 11:45:19 am] No plugin was found for the platform "Ecowitt" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Plugin Config:**
{
    "bridge": {
        "name": "Homebridge ",
        "username": "",
        "port": 51765,
        "pin": "",
        "advertiser": "bonjour-hap"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 80,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
{
            "mac": "FC:F5:C4:8D:43:34",
            "port": 4199,
            "path": "/weather/data/",
            "ws": {
                "hide": false,
                "uv": {
                    "hide": false,
                    "threshold": 6
                },
                "solarradiation": {
                    "hide": false,
                    "luxFactor": 126.7
                },
                "wind": {
                    "units": "kmh",
                    "speedThreshold": 1,
                    "gustThreshold": 3,
                    "maxDailyGustThreshold": 8
                },
                "rain": {
                    "units": "mm"
                }
            },
            "thbin": {
                "hide": false
            },
            "th": {
                "hide": false,
                "name1": "CH1",
                "name2": "CH2"
            },
            "soil": {
                "hide": true
            },
            "leak": {
                "hide": true
            },
            "pm25": {
                "hide": true
            },
            "lightning": {
                "hide": true,
                "units": "km"
            },
            "platform": "Ecowitt"
        }

**Environment:**

* **Plugin Version**: homebridge-ecowitt v1.1.0
* **Homebridge Version**: 1.5.1
* **Node.js Version**: v18.12.0
* **NPM Version**: 8.19.2
* **Operating System**: Linux hmb 5.10.0-19-amd64 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

**Comment by LordJohnWhorfin** [comment]
I'm having the same problem since updating to node.js 18

**Comment by anthonyb82** [comment]
I’m seeing the same when updating to node.js 18 as well. Rolled back to 16 and it’s working fine again.

**Comment by rhockenbury** [comment]
Hi @gwurb, @LordJohnWhorfin, @anthonyb82.  I have a new Ecowitt plugin available (v2), check out [Homebridge Ecowitt Weather Sensors](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors) which can be installed through the Homebridge UI. This new plugin works with node 18, node 20, and node 22 (regression tests for all 3 node versions run on every build).  Would appreciate any feedback if you have time to give this new version a try, and [let me know if you hit any issues](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/issues/new).
