### ISSUE TITLE
getting errors trying to connect

### ISSUE THREAD

**Issue by doublejj0321** [spatialdude/homebridge-ecowitt#23]
Unable to install without getting errors, any ideas?

====================
[01/11/2022, 07:52:19] ERROR LOADING PLUGIN homebridge-ecowitt:
[01/11/2022, 07:52:19] TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (/usr/local/lib/node_modules/homebridge-ecowitt/node_modules/restify/lib/request.js:848:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ecowitt/node_modules/restify/lib/server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ecowitt/node_modules/restify/lib/index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
[01/11/2022, 07:52:19] ====================

   "mac": "30:83:98:A7:18:A3",
    "port": 8080,
    "path": "/data/report/",
    "ws": {
        "hide": true,
        "uv": {
            "hide": false,
            "threshold": 6
        },
        "solarradiation": {
            "hide": false,
            "luxFactor": 126.7
        },
        "wind": {
            "units": "beaufort",
            "speedThreshold": 1,
            "gustThreshold": 3,
            "maxDailyGustThreshold": 8
        },
        "rain": {
            "units": "mm"
        }
    },
    "thbin": {
        "hide": true
    },
    "th": {
        "hide": false,
        "name1": "one",
        "name2": "two"
    },
    "soil": {
        "hide": true
    },
    "leak": {
        "hide": true
    },
    "pm25": {
        "hide": true
    },
    "lightning": {
        "hide": true,
        "units": "km"
    },
    "platform": "Ecowitt"
}

**Comment by LordJohnWhorfin** [comment]
Roll back node.js to v17

**Comment by TurboSasch** [comment]
Same problem here. Is it possible, that the plugin could upgrade to the actually node.js?

**Comment by rhockenbury** [comment]
Hi @doublejj0321, @LordJohnWhorfin, @TurboSasch.  If you are still looking for a solution, I have a new Ecowitt plugin available (v2), check out [Homebridge Ecowitt Weather Sensors](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors) which can be installed through the Homebridge UI.  This new plugin no longer uses Restify which is throwing the error mentioned above.  Would appreciate any feedback if you have time to give this new version a try, and [let me know if you hit any issues](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/issues/new).

**Comment by LordJohnWhorfin** [comment]
Hi Ryler,Thanks for letting me know, I filed a bug report about WH31 support. Let me know if I can do anything to help!EricOn Sep 13, 2024, at 12:13 PM, Ryler Hockenbury ***@***.***> wrote:﻿
Hi @doublejj0321, @LordJohnWhorfin, @TurboSasch.  If you are still looking for a solution, I have a new Ecowitt plugin available (v2), check out Homebridge Ecowitt Weather Sensors which can be installed through the Homebridge UI.  This new plugin no longer uses Restify which is throwing the error mentioned above.  Would appreciate any feedback if you have time to give this new version a try, and let me know if you hit any issues.
