### ISSUE TITLE
Reload of homebridge  causes SIGTERM

### ISSUE THREAD

**Issue by mbrowny** [spatialdude/homebridge-ecowitt#3]
**Describe The Bug:**
When you change any configuration in home bridge and restart the homebridge service, the EcoWitt plugin causes a SIGTERM while trying to restore existing accessory from cache. 

**To Reproduce:**
Just change any homebridge configuration and restart the service.

**Expected behavior:**
No crash...

**Logs:**

```
[17/05/2021, 8:48:13 pm] [Ecowitt] sensorId: XX:XX:XX:XX:XX:F9-GW1000 uuid: XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX
[17/05/2021, 8:48:13 pm] [Ecowitt] Restoring existing accessory from cache: GW1000
[17/05/2021, 8:48:13 pm] Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:609:13)
    at Bridge.Accessory.removeBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:622:12)
    at BridgeService.handleUnregisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:402:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:355:10)
    at EcowittPlatform.registerAccessories (/usr/lib/node_modules/homebridge-ecowitt/src/EcowittPlatform.ts:267:18)
    at EcowittPlatform.onDataReport (/usr/lib/node_modules/homebridge-ecowitt/src/EcowittPlatform.ts:136:12)
    at /usr/lib/node_modules/homebridge-ecowitt/src/EcowittPlatform.ts:82:14
    at nextTick (/usr/lib/node_modules/homebridge-ecowitt/node_modules/restify/lib/chain.js:167:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[17/05/2021, 8:48:13 pm] Got SIGTERM, shutting down Homebridge...
[17/05/2021, 8:48:18 pm] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[17/05/2021, 8:48:23 pm] [HB Supervisor] Restarting Homebridge...
```

**Environment:**

* **Plugin Version**: 1.1.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Operating System**: Ubuntu

**Comment by spatialdude** [comment]
Thanks @mbrowny I haven't yet observed the SIGTERM occurring as you describe above. I wonder if this is related to https://github.com/spatialdude/homebridge-ecowitt/issues/2#issuecomment-944851871. Are you still seeing this happening?

**Comment by mbrowny** [comment]
yes still the same:
[12/07/2022, 7:15:53 pm] [Ecowitt] Restoring existing accessory from cache: GW1000
[12/07/2022, 7:15:53 pm] Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:640:13)
    at Bridge.Accessory.removeBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:654:12)
    at BridgeService.handleUnregisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (events.js:400:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:355:10)
    at EcowittPlatform.registerAccessories (/usr/lib/node_modules/homebridge-ecowitt/src/EcowittPlatform.ts:267:18)
    at EcowittPlatform.onDataReport (/usr/lib/node_modules/homebridge-ecowitt/src/EcowittPlatform.ts:136:12)
    at /usr/lib/node_modules/homebridge-ecowitt/src/EcowittPlatform.ts:82:14
    at nextTick (/usr/lib/node_modules/homebridge-ecowitt/node_modules/restify/lib/chain.js:167:13)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[12/07/2022, 7:15:53 pm] Got SIGTERM, shutting down Homebridge...
[12/07/2022, 7:15:58 pm] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/07/2022, 7:16:03 pm] [HB Supervisor] Restarting Homebridge...
[12/07/2022, 7:16:03 pm] [HB Supervisor] Starting Homebridge with extra flags: -I -D

**Comment by Elephantoplasty** [comment]
I've just installed this, and also get this error.

Having reproduced it a couple of times, I'm pretty sure that the error doesn't occurs if I have the gateway page open and I'm logged in.  So it starts fine and creates accessories and reports if the gateway is open at the time I start HB.

Mine is a new GW1100, says 'Version: GW1100C_V2.1.8'.

**Comment by abrainwood** [comment]
I've got the same problem. I've tried with a GW1000C and a HP2551, same result either way. Using Homebridge 1.6.0 on Node 16.18.0 and homebridge-ecowitt v1.1.0. Have also tried version v1.0.0 but get the same result:

```[11/12/2022, 22:47:14] [Ecowitt] Restoring existing accessory from cache: WH65
[11/12/2022, 22:47:14] Got SIGTERM, shutting down Homebridge...
[11/12/2022, 22:44:26] [Ecowitt] Restoring existing accessory from cache: WH65
[11/12/2022, 22:44:26] Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:437:19)
    at Bridge.Accessory.removeBridgedAccessories (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:452:22)
    at BridgeService.handleUnregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/lib/bridgeService.js:293:21)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/lib/api.js:151:14)
    at EcowittPlatform.registerAccessories (/var/lib/homebridge/node_modules/homebridge-ecowitt/dist/EcowittPlatform.js:216:26)
    at EcowittPlatform.onDataReport (/var/lib/homebridge/node_modules/homebridge-ecowitt/dist/EcowittPlatform.js:112:18)
    at /var/lib/homebridge/node_modules/homebridge-ecowitt/dist/EcowittPlatform.js:73:18
    at nextTick (/var/lib/homebridge/node_modules/homebridge-ecowitt/node_modules/restify/lib/chain.js:167:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

[11/12/2022, 22:44:26] Got SIGTERM, shutting down Homebridge...
[11/12/2022, 22:44:31] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/12/2022, 22:44:36] [HB Supervisor] Restarting Homebridge...
[11/12/2022, 22:44:36] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[11/12/2022, 22:44:36] [HB Supervisor] Started Homebridge v1.6.0```
